### ISSUE TITLE
Cannot run on HTC 10 in Unity

### ISSUE THREAD

**Issue by areong** [tomthecarrot/arcore-for-all#2]
# Problem

I've replaced `unitygar.aar` with yours and followed the official tutorial for Unity, but the built apk cannot run on my HTC 10. The app closes right after being opened. The HTC 10 runs android 7.0.

**Comment by MZorzy** [comment]
same as Update sample APK
#1

**Comment by jinqian** [comment]
not working on Nexus 5x and 6P either

**Comment by tomthecarrot** [comment]
Could you attach logcat output of the crash? Please also keep in mind that this is experimental.

**Comment by tomthecarrot** [comment]
Please try with this suggestion:
https://github.com/tomthecarrot/arcore-for-all/issues/3#issuecomment-326015422

**Comment by secretxu** [comment]
both unity apk and sample apk can't work on my galaxy s8+

**Comment by tomthecarrot** [comment]
@secretxu did you install the ARCore Service APK before installing the samples?

**Comment by secretxu** [comment]
yes

**Comment by areong** [comment]
@tomthecarrot Oh I missed that step! I'll install ARCore Service and try again, thx!

**Comment by secretxu** [comment]
@areong can it work after installing ARCore service?

**Comment by areong** [comment]
@secretxu No. The ARCore Service (also called Tango Core) can be installed, but stopped immediately after I opened HelloAR. HelloAR also stops after ARCore Service stops.

**Comment by secretxu** [comment]
@areong my ARCore Service can also be installed and didn't stop, but helloAR stopped immediately after unity splash. I thought our ARCore Service may be different with @tomthecarrot.

**Comment by khursani8** [comment]
@tomthecarrot can you reproduce the step on how you create and install the apk. Maybe you missing something in the README.

**Comment by areong** [comment]
@secretxu My ARCore Service is installed from `arcore-preview.apk` from https://github.com/google-ar/arcore-android-sdk/releases/tag/sdk-preview, which is what the official guide describes. Maybe the official ARCore Service also checks the "supported devices".

**Comment by secretxu** [comment]
@khursani8 same as @areong , and give ARCore Service device permissions.

**Comment by tomthecarrot** [comment]
@areong that is possible. The modified ARCore is working fine on my S8 Plus, which is not an officially supported device. However, it is similar to the S8, and I wonder if they are checking something else (like CPU architecture).

**Comment by raichuk** [comment]
First of all @tomthecarrot many thanks for this work and all your efforts (and I love the repo name!).

On my Moto G4 with Android 7 I tried the ARCore Service with the link that @areong provides and then installed you sample apk.
When I start the HelloAR apk, first, crashes Tanto Service and then HelloAR.

I don´t know how to logcat, but if it is helpful for you.. I try.

**Comment by khursani8** [comment]
@tomthecarrot probably because my device nexus 5 is ARM and S8 Plus is ARMx64

**Comment by tomthecarrot** [comment]
Thank you for your kind words @raichuk! I want to help make this work for everyone :)

**Comment by tomthecarrot** [comment]
@khursani8 Thanks for the info. Adding to the research.

**Comment by tomthecarrot** [comment]
Added the known devices to a [research document](https://github.com/tomthecarrot/arcore-for-all/blob/master/Device-Research.md) to try to isolate the issue. I appreciate any help with feedback, modifications, and pull requests.

**Comment by areong** [comment]
@tomthecarrot Here is the log shown in the Android Studio logcat, thank you:

```
09-01 10:41:53.239 27202-27202/? I/art: Late-enabling -Xcheck:jni
09-01 10:41:53.239 27202-27202/? I/art: VMHOOK: rlim_cur : 0 pid:27202
09-01 10:41:53.371 27202-27202/com.google.ar.core.examples.java.helloar W/System: ClassLoader referenced unknown path: /data/app/com.google.ar.core.examples.java.helloar-2/lib/arm64
09-01 10:41:53.387 27202-27202/com.google.ar.core.examples.java.helloar I/InstantRun: starting instant run server: is main process
09-01 10:41:53.440 27202-27202/com.google.ar.core.examples.java.helloar W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-01 10:41:53.491 27202-27202/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
09-01 10:41:53.512 27202-27202/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
09-01 10:41:53.517 27202-27202/com.google.ar.core.examples.java.helloar I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
09-01 10:41:53.533 27202-27202/com.google.ar.core.examples.java.helloar I/ndk_camera: Starting native camera system initialization.
09-01 10:41:53.535 27202-27202/com.google.ar.core.examples.java.helloar D/ndk_camera: Camera 0 has 88 metadata tags
09-01 10:41:53.535 27202-27202/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
09-01 10:41:53.535 27202-27202/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1310721 for camera 0 with error code -10004
09-01 10:41:53.535 27202-27202/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
09-01 10:41:53.535 27202-27202/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1638401 for camera 0 with error code -10004
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar D/ndk_camera: Camera 1 has 87 metadata tags
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1310721 for camera 1 with error code -10004
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1638401 for camera 1 with error code -10004
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar I/ndk_camera: Camera system initialized successfully with 2 cameras.
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: Camera system initilized.
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar E/tango_camera_native: 2 is not a valid camera index.
09-01 10:41:53.536 27202-27202/com.google.ar.core.examples.java.helloar E/tango_camera_native: 3 is not a valid camera index.
09-01 10:41:53.540 27202-27202/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching texture_window 0x7fa62a8e10
09-01 10:41:53.540 27202-27202/com.google.ar.core.examples.java.helloar D/TangoVhs: about to bind as vhs
09-01 10:41:53.553 27202-27202/com.google.ar.core.examples.java.helloar D/TangoVhs: finished bind as vhs
09-01 10:41:53.605 27202-27246/com.google.ar.core.examples.java.helloar I/Adreno: QUALCOMM build                   : 28fbe1e, I1c3536cac6
                                                                                  Build Date                       : 12/27/16
                                                                                  OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                                  Local Branch                     : 
                                                                                  Remote Branch                    : 
                                                                                  Remote Branch                    : 
                                                                                  Reconstruct Branch               : 
09-01 10:41:54.012 27202-27202/com.google.ar.core.examples.java.helloar D/TangoVhs: connected
09-01 10:41:54.013 27202-27262/com.google.ar.core.examples.java.helloar I/TangoCameraNative: Tango VHS Ready
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err: android.os.DeadObjectException
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transact(Binder.java:623)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
09-01 10:41:54.221 27202-27262/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases
09-01 10:41:56.938 27202-27207/com.google.ar.core.examples.java.helloar I/art: Do partial code cache collection, code=29KB, data=29KB
09-01 10:41:56.938 27202-27207/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=24KB, data=26KB
09-01 10:41:56.938 27202-27207/com.google.ar.core.examples.java.helloar I/art: Increasing code cache capacity to 128KB
```

**Comment by tomthecarrot** [comment]
`Tango VHS Ready`? That's an interesting error. Let's look into it.

**Comment by areong** [comment]
@tomthecarrot I didn't notice that you've uploaded the modified ARCore Service. I'll try it.

**Comment by tomthecarrot** [comment]
Great, thank you @areong!

**Comment by areong** [comment]
@tomthecarrot The modified ARCore Service also stops right after I opened the HelloAR. So sad. I'll print the log when I'm back home this night. Thank you.

**Comment by areong** [comment]
@tomthecarrot This is the log using the modified ARCore Service. This time `Tango VHS Ready` shows up again after the `DeadObjectException`.

```
09-02 01:19:28.921 23886-23886/? I/art: Late-enabling -Xcheck:jni
09-02 01:19:28.921 23886-23886/? I/art: VMHOOK: rlim_cur : 0 pid:23886
09-02 01:19:28.935 23886-23893/? I/art: Ignoring second debugger -- accepting and dropping
09-02 01:19:28.956 23886-23893/? I/art: Debugger is no longer active
09-02 01:19:28.956 23886-23893/? I/art: Starting a blocking GC Instrumentation
09-02 01:19:29.047 23886-23886/? W/System: ClassLoader referenced unknown path: /data/app/com.google.ar.core.examples.java.helloar-2/lib/arm64
09-02 01:19:29.065 23886-23886/? I/InstantRun: starting instant run server: is main process
09-02 01:19:29.117 23886-23886/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-02 01:19:29.168 23886-23886/? E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
09-02 01:19:29.187 23886-23886/? E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
09-02 01:19:29.192 23886-23886/? I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
09-02 01:19:29.208 23886-23886/? I/ndk_camera: Starting native camera system initialization.
09-02 01:19:29.210 23886-23886/? D/ndk_camera: Camera 0 has 88 metadata tags
09-02 01:19:29.210 23886-23886/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
09-02 01:19:29.210 23886-23886/? W/ndk_camera: Failed to get metadata tag 1310721 for camera 0 with error code -10004
09-02 01:19:29.210 23886-23886/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
09-02 01:19:29.210 23886-23886/? W/ndk_camera: Failed to get metadata tag 1638401 for camera 0 with error code -10004
09-02 01:19:29.210 23886-23886/? D/ndk_camera: Camera 1 has 87 metadata tags
09-02 01:19:29.210 23886-23886/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
09-02 01:19:29.210 23886-23886/? W/ndk_camera: Failed to get metadata tag 1310721 for camera 1 with error code -10004
09-02 01:19:29.210 23886-23886/? E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
09-02 01:19:29.210 23886-23886/? W/ndk_camera: Failed to get metadata tag 1638401 for camera 1 with error code -10004
09-02 01:19:29.211 23886-23886/? I/ndk_camera: Camera system initialized successfully with 2 cameras.
09-02 01:19:29.211 23886-23886/? W/tango_camera_native_jni: Camera system initilized.
09-02 01:19:29.211 23886-23886/? E/tango_camera_native: 2 is not a valid camera index.
09-02 01:19:29.211 23886-23886/? E/tango_camera_native: 3 is not a valid camera index.
09-02 01:19:29.215 23886-23886/? I/tango_camera_native_jni: Attaching texture_window 0x7fa62a8e10
09-02 01:19:29.215 23886-23886/? D/TangoVhs: about to bind as vhs
09-02 01:19:29.228 23886-23886/? D/TangoVhs: finished bind as vhs
09-02 01:19:29.263 23886-23918/? I/Adreno: QUALCOMM build                   : 28fbe1e, I1c3536cac6
                                           Build Date                       : 12/27/16
                                           OpenGL ES Shader Compiler Version: XE031.09.00.04
                                           Local Branch                     : 
                                           Remote Branch                    : 
                                           Remote Branch                    : 
                                           Reconstruct Branch               : 
09-02 01:19:29.693 23886-23886/? D/TangoVhs: connected
09-02 01:19:29.714 23886-23926/? I/TangoCameraNative: Tango VHS Ready
09-02 01:19:29.895 23886-23926/? W/System.err: android.os.DeadObjectException
09-02 01:19:29.895 23886-23926/? W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
09-02 01:19:29.895 23886-23926/? W/System.err:     at android.os.BinderProxy.transact(Binder.java:623)
09-02 01:19:29.895 23886-23926/? W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
09-02 01:19:29.895 23886-23926/? W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
09-02 01:19:29.895 23886-23926/? W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
09-02 01:19:29.895 23886-23926/? W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-02 01:19:29.895 23886-23926/? I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
09-02 01:19:29.895 23886-23926/? W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases
09-02 01:19:31.012 23886-23886/com.google.ar.core.examples.java.helloar D/TangoVhs: connected
09-02 01:19:31.012 23886-23967/com.google.ar.core.examples.java.helloar I/TangoCameraNative: Tango VHS Ready
09-02 01:19:31.016 23886-23967/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
09-02 01:19:31.016 23886-23967/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching tracking_window 0x7f7f891010
09-02 01:19:32.620 23886-23891/com.google.ar.core.examples.java.helloar I/art: Do partial code cache collection, code=29KB, data=29KB
09-02 01:19:32.620 23886-23891/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=24KB, data=26KB
09-02 01:19:32.620 23886-23891/com.google.ar.core.examples.java.helloar I/art: Increasing code cache capacity to 128KB
```
