### ISSUE TITLE
Cannot run on Android

### ISSUE THREAD

**Issue by pavelupward** [tomthecarrot/arcore-for-all#3]
error in config

**Comment by tomthecarrot** [comment]
Please explain in more detail. Can you post logcat output?

**Comment by pavelupward** [comment]
@tomthecarrot 
`08-30 17:08:03.284 17015-17015/com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.google.ar.core.examples.java.helloar, PID: 17015
                                                                                          java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                                                              at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                                                              at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                                                              at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                                                              at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                                                              at com.google.ar.core.Session.resume(Session.java:153)
                                                                                              at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:136)
                                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                                              at android.app.Activity.performResume(Activity.java:6665)
                                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3122)
                                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3164)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5468)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

line:
 mSession.resume(mDefaultConfig);

android 6.0
in gradle  i changed  minSdkVersion 23
in \app\libs    i changed

now in folder \app\libs
obj-0.2.1
arcore_client    -i copy this  in your project

**Comment by pavelupward** [comment]
No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)

**Comment by Horsetopus** [comment]
Have you installed the ARCore service APK?
If not follow the instructions in "Prepare your device".
https://developers.google.com/ar/develop/java/getting-started

**Comment by pavelupward** [comment]
@Horsetopus 
ARCore service  android 7.0?

**Comment by Horsetopus** [comment]
Should be it. 7.0 is the minimum requirement.
Anyway they let you download it on the link I gave you.
Just give it a try to be sure you have the right version.

**Comment by tomthecarrot** [comment]
Thank you @Horsetopus! During development I had installed ARCore Service on my device, but forgot to add it to the README. Will add now.

**Comment by pavelupward** [comment]
@Horsetopus 
i have android 6.0((

**Comment by tomthecarrot** [comment]
Below minimum OS
