### ISSUE TITLE
Crash on Nexus 6

### ISSUE THREAD

**Issue by alexglobalbit** [tomthecarrot/arcore-for-all#38]
09-04 11:40:36.347 23022-23022/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.tango, PID: 23022
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.tango-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.tango-1/lib/arm, /system/fake-libs, /data/app/com.google.tango-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libtango_hal.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                       at java.lang.System.loadLibrary(System.java:1530)
                                                       at com.google.atap.tango.TangoVirtualHalService.<clinit>(TangoVirtualHalService.java:41)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3173)
                                                       at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by marjan89** [comment]
Same here, Nexus 6 OS: 7.1.1:

09-07 20:08:49.942 2102-2121/? I/ActivityManager: Start proc 23134:com.google.tango/u0a144 for service com.google.tango/com.google.atap.tango.TangoVirtualHalService
09-07 20:08:50.008 23134-23134/? D/AndroidRuntime: Shutting down VM
09-07 20:08:50.009 23134-23134/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.tango, PID: 23134
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.tango-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.tango-1/lib/arm, /system/fake-libs, /data/app/com.google.tango-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libtango_hal.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                       at java.lang.System.loadLibrary(System.java:1530)
                                                       at com.google.atap.tango.TangoVirtualHalService.<clinit>(TangoVirtualHalService.java:41)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3173)
                                                       at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
