### ISSUE TITLE
Xiaomi Redmi note 4 Global Version, Android 7.0 [Not Working] [Logs]

### ISSUE THREAD

**Issue by dryn27** [tomthecarrot/arcore-for-all#41]
* * * * * * * * * * * * * * * *
Build fingerprint: 'xiaomi/mido/mido:7.0/NRD90M/V8.5.4.0.NCFMIED:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 7956, tid: 7956, name: om.google.tango  >>> com.google.tango <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'calibration_provider.cc:589 Check failed: parse_cad_error_code == LoadCalibrationXmlErrorCode::kSuccess '
    x0   0000000000000000  x1   0000000000001f14  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000808080  x6   0000007f7f1cb000  x7   0000000000000000
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000000  x14  0000000000000000  x15  0034c9dc87cc0f39
    x16  0000007f7eaf3ed0  x17  0000007f7ea9d510  x18  0000000000000000  x19  0000007f7f27eb40
    x20  0000000000000006  x21  0000007f7f27ea98  x22  0000000000000002  x23  0000007fd4446ac8
    x24  0000000000000068  x25  0000007f7b516918  x26  0000007f705c8240  x27  0000007f70526020
    x28  0000007f70525ff8  x29  0000007fd44464a0  x30  0000007f7ea9a9a0
    sp   0000007fd4446480  pc   0000007f7ea9d518  pstate 0000000060000000

backtrace:
    #00 pc 000000000006b518  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000006899c  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023ee8  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c96c  /system/lib64/libc.so (abort+52)
    #04 pc 0000000000005a40  /system/lib64/liblog.so (__android_log_assert+232)
    #05 pc 0000000000100718  /data/app/com.google.tango-2/lib/arm64/libtango_service_library.so (_ZN13MessageLoggerD2Ev+4120)
    #06 pc 0000000000c8433c  /data/app/com.google.tango-2/lib/arm64/libtango_service_library.so
    #07 pc 0000000000c85be8  /data/app/com.google.tango-2/lib/arm64/libtango_service_library.so
    #08 pc 0000000000129150  /data/app/com.google.tango-2/lib/arm64/libtango_service_library.so (_ZN13tango_service12TangoContextC1ESt10shared_ptrINS_15JniTangoServiceEE+512)
    #09 pc 000000000013c80c  /data/app/com.google.tango-2/lib/arm64/libtango_service_library.so (_ZN12tango_binder7ServiceC2ESt10shared_ptrIN13tango_service15JniTangoServiceEE+228)
    #10 pc 000000000013a238  /data/app/com.google.tango-2/lib/arm64/libtango_service_library.so (Java_com_google_atap_tango_TangoServiceJNINative_CreateNativeService+972)
    #11 pc 00000000007f5e98  /data/app/com.google.tango-2/oat/arm64/base.odex (offset 0x7a7000)

**Comment by tomthecarrot** [comment]
Thanks for sharing your log! It is helpful in debugging the issue.

**Comment by fazpeerbaksh** [comment]
I used the  modified apk and libraries but it doesn't work, app opens but no camera feed only black screen. Also like to point out that in the log it says Zero Camera found for native camera
here's the log


09-13 14:00:58.794 17899-17942/com.google.ar.core.examples.java.helloar I/Adreno: QUALCOMM build                   : 01d2d27, I3d52eaf367
                                                                                  Build Date                       : 12/10/16
                                                                                  OpenGL ES Shader Compiler Version: XE031.09.00.03
                                                                                  Local Branch                     : 
                                                                                  Remote Branch                    : 
                                                                                  Remote Branch                    : 
                                                                                  Reconstruct Branch               : 
09-13 14:00:58.800 17899-17942/com.google.ar.core.examples.java.helloar I/OpenGLRenderer: Initialized EGL, version 1.4
09-13 14:00:58.800 17899-17942/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: Swap behavior 1
09-13 14:01:02.126 17899-17899/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
09-13 14:01:02.127 17899-17899/com.google.ar.core.examples.java.helloar I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
09-13 14:01:02.167 17899-17899/com.google.ar.core.examples.java.helloar I/ndk_camera: Starting native camera system initialization.
09-13 14:01:02.173 17899-17899/com.google.ar.core.examples.java.helloar I/ndk_camera: Zero cameras detected. Camera system initialization complete
09-13 14:01:02.174 17899-17899/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: Camera system initilized.
09-13 14:01:02.174 17899-17899/com.google.ar.core.examples.java.helloar E/tango_camera_native: 0 is not a valid camera index.
09-13 14:01:02.174 17899-17899/com.google.ar.core.examples.java.helloar E/tango_camera_native: 1 is not a valid camera index.
09-13 14:01:02.174 17899-17899/com.google.ar.core.examples.java.helloar E/tango_camera_native: 2 is not a valid camera index.
09-13 14:01:02.174 17899-17899/com.google.ar.core.examples.java.helloar E/tango_camera_native: 3 is not a valid camera index.
09-13 14:01:02.181 17899-17899/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching texture_window 0x7fabe56a10
09-13 14:01:02.181 17899-17899/com.google.ar.core.examples.java.helloar D/TangoVhs: about to bind as vhs
09-13 14:01:02.200 17899-17899/com.google.ar.core.examples.java.helloar D/TangoVhs: finished bind as vhs
09-13 14:01:02.697 17899-17904/com.google.ar.core.examples.java.helloar I/art: Do partial code cache collection, code=28KB, data=26KB
09-13 14:01:02.697 17899-17904/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=24KB, data=23KB
09-13 14:01:02.697 17899-17904/com.google.ar.core.examples.java.helloar I/art: Increasing code cache capacity to 128KB
09-13 14:01:02.836 17899-17899/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
09-13 14:01:02.921 17899-17899/com.google.ar.core.examples.java.helloar D/TangoVhs: connected
09-13 14:01:02.926 17899-18240/com.google.ar.core.examples.java.helloar I/TangoCameraNative: Tango VHS Ready
09-13 14:01:03.199 17899-18240/com.google.ar.core.examples.java.helloar W/System.err: android.os.DeadObjectException
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transact(Binder.java:615)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
09-13 14:01:03.203 17899-18240/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases
