### ISSUE TITLE
Xiaomi mi4c not working

### ISSUE THREAD

**Issue by xavis** [tomthecarrot/arcore-for-all#46]
Her are my logs from the sample.apk offered

```
09-05 13:02:21.758: A/tango(18765): jni_helper.cc:19 'vm' Must be non NULL
09-05 13:02:21.758: A/libc(18765): Fatal signal 6 (SIGABRT), code -6 in tid 18781 (UnityMain)
09-05 13:02:21.759: W/(336): debuggerd: handling request: pid=18765 uid=10099 gid=10099 tid=18781
09-05 13:02:21.873: A/DEBUG(18835): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-05 13:02:21.873: A/DEBUG(18835): LineageOS Version: '14.1-20170823-NIGHTLY-libra'
09-05 13:02:21.874: A/DEBUG(18835): Build fingerprint: 'Xiaomi/libra/libra:7.0/NRD90M/V8.2.3.0.NXKCNEC:user/release-keys'
09-05 13:02:21.874: A/DEBUG(18835): Revision: '0'
09-05 13:02:21.874: A/DEBUG(18835): ABI: 'arm'
09-05 13:02:21.874: A/DEBUG(18835): pid: 18765, tid: 18781, name: UnityMain  >>> com.tomthecarrot.helloar <<<
09-05 13:02:21.874: A/DEBUG(18835): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-05 13:02:21.891: A/DEBUG(18835): Abort message: 'jni_helper.cc:19 'vm' Must be non NULL'
09-05 13:02:21.891: A/DEBUG(18835):     r0 00000000  r1 0000495d  r2 00000006  r3 00000008
09-05 13:02:21.892: A/DEBUG(18835):     r4 f2ed7978  r5 00000006  r6 f2ed7920  r7 0000010c
09-05 13:02:21.892: A/DEBUG(18835):     r8 f2ed5cc0  r9 f2ed5cbc  sl 00000515  fp f2ed5fd0
09-05 13:02:21.892: A/DEBUG(18835):     ip 00000002  sp f2ed5840  lr f66dd127  pc f66df984  cpsr 200f0010
09-05 13:02:21.902: A/DEBUG(18835): backtrace:
09-05 13:02:21.902: A/DEBUG(18835):     #00 pc 0004a984  /system/lib/libc.so (tgkill+12)
09-05 13:02:21.902: A/DEBUG(18835):     #01 pc 00048123  /system/lib/libc.so (pthread_kill+34)
09-05 13:02:21.903: A/DEBUG(18835):     #02 pc 0001d985  /system/lib/libc.so (raise+10)
09-05 13:02:21.903: A/DEBUG(18835):     #03 pc 000194d1  /system/lib/libc.so (__libc_android_abort+34)
09-05 13:02:21.903: A/DEBUG(18835):     #04 pc 00017118  /system/lib/libc.so (abort+4)
09-05 13:02:21.903: A/DEBUG(18835):     #05 pc 00005841  /system/lib/liblog.so (__android_log_assert+112)
09-05 13:02:21.903: A/DEBUG(18835):     #06 pc 00009e69  /data/app/com.tomthecarrot.helloar-1/lib/arm/libtango_client_api2.so
09-05 13:02:21.904: A/DEBUG(18835):     #07 pc 0001256d  /data/app/com.tomthecarrot.helloar-1/lib/arm/libtango_client_api2.so
09-05 13:02:21.904: A/DEBUG(18835):     #08 pc 00009247  /data/app/com.tomthecarrot.helloar-1/lib/arm/libtango_client_api2.so (TangoService_isSupported+26)
09-05 13:02:21.904: A/DEBUG(18835):     #09 pc 00009704  <anonymous:d7400000>
09-05 13:02:22.096: I/MSM-irqbalance(449): Decided to move IRQ51 from CPU2 to CPU3
09-05 13:02:22.357: I/AudioFlinger(409): BUFFER TIMEOUT: remove(4096) from active list on thread 0xf4f83940
09-05 13:02:23.318: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:23.413: W/ActivityManager(2065):   Force finishing activity com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity
09-05 13:02:23.415: I/BootReceiver(2065): Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
09-05 13:02:23.415: W/(336): debuggerd: resuming target 18765
09-05 13:02:23.437: E/lowmemorykiller(385): Error writing /proc/18765/oom_score_adj; errno=22
09-05 13:02:23.438: W/ActivityManager(2065): Failed setting process group of 18765 to 1
09-05 13:02:23.438: W/System.err(2065): java.lang.IllegalArgumentException: Given thread 18782 does not exist
09-05 13:02:23.438: W/System.err(2065): 	at android.os.Process.setThreadPriority(Native Method)
09-05 13:02:23.438: W/System.err(2065): 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20780)
09-05 13:02:23.438: W/System.err(2065): 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21313)
09-05 13:02:23.438: W/System.err(2065): 	at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:274)
09-05 13:02:23.438: W/System.err(2065): 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1225)
09-05 13:02:23.438: W/System.err(2065): 	at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:172)
09-05 13:02:23.438: W/System.err(2065): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-05 13:02:23.438: W/System.err(2065): 	at android.os.Looper.loop(Looper.java:154)
09-05 13:02:23.438: W/System.err(2065): 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-05 13:02:23.438: W/System.err(2065): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-05 13:02:23.464: D/GraphicsStats(2065): Buffer count: 8
09-05 13:02:23.466: I/ActivityManager(2065): Process com.tomthecarrot.helloar (pid 18765) has died
09-05 13:02:23.466: D/ActivityManager(2065): cleanUpApplicationRecord -- 18765
09-05 13:02:23.474: E/FrameworkListener(418): read() failed (Connection reset by peer)
09-05 13:02:23.474: W/InputDispatcher(2065): channel 'd79b2ea com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-05 13:02:23.475: E/InputDispatcher(2065): channel 'd79b2ea com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-05 13:02:23.475: I/Zygote(408): Process 18765 exited due to signal (6)
09-05 13:02:23.476: I/OpenGLRenderer(2065): Initialized EGL, version 1.4
09-05 13:02:23.477: D/OpenGLRenderer(2065): Swap behavior 1
09-05 13:02:23.483: I/WindowManager(2065): WIN DEATH: Window{d79b2ea u0 com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity}
09-05 13:02:23.484: W/InputDispatcher(2065): Attempted to unregister already unregistered input channel 'd79b2ea com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity (server)'
09-05 13:02:23.484: W/WindowManager(2065): Force-removing child win Window{c7b3c78 u0 SurfaceView - com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity} from container Window{d79b2ea u0 com.tomthecarrot.helloar/com.unity3d.player.UnityPlayerActivity}
09-05 13:02:23.490: W/WindowManager(2065): Failed looking up window
09-05 13:02:23.490: W/WindowManager(2065): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@c50a9db does not exist
09-05 13:02:23.490: W/WindowManager(2065): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9462)
09-05 13:02:23.490: W/WindowManager(2065): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9453)
09-05 13:02:23.490: W/WindowManager(2065): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
09-05 13:02:23.490: W/WindowManager(2065): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
09-05 13:02:23.490: I/WindowManager(2065): WIN DEATH: null
09-05 13:02:24.881: D/audio_hw_primary(409): out_standby: enter: stream (0xf5e78300) usecase(0: deep-buffer-playback)
09-05 13:02:25.105: D/audio_hw_primary(409): disable_audio_route: reset and update mixer path: deep-buffer-playback
09-05 13:02:25.110: D/soundtrigger(409): audio_extn_sound_trigger_update_stream_status: uc_id 0 of type 0 for Event 2, with Raise=0
09-05 13:02:25.111: D/hardware_info(409): hw_info_append_hw_type : device_name = speaker
09-05 13:02:25.111: D/audio_hw_primary(409): disable_snd_device: snd_device(2: speaker)
09-05 13:02:25.127: D/hardware_info(409): hw_info_append_hw_type : device_name = vi-feedback
09-05 13:02:25.128: D/audio_hw_primary(409): disable_snd_device: snd_device(81: vi-feedback)
09-05 13:02:25.128: I/soundtrigger(409): audio_extn_sound_trigger_update_device_status: device 0x51 of type 1 for Event 0, with Raise=0
09-05 13:02:25.128: D/audio_hw_primary(409): disable_audio_route: reset and update mixer path: spkr-vi-record
09-05 13:02:25.128: D/soundtrigger(409): audio_extn_sound_trigger_update_stream_status: uc_id 36 of type 1 for Event 2, with Raise=0
09-05 13:02:25.133: I/soundtrigger(409): audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0, with Raise=0
09-05 13:02:26.333: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:26.342: D/WifiStateMachine(2065): updateCapabilities for config:ANSWAREfalse,false
09-05 13:02:26.577: D/LuxLevels(2065): bright hysteresis constant= 0.1, threshold=73.16488, lux=66.51353
09-05 13:02:26.578: D/LuxLevels(2065): dark hysteresis constant= 0.2, threshold=53.210823, lux=66.51353
09-05 13:02:26.661: I/WCNSS_FILTER(6616): ibs_msm_serial_clock_vote: vote UART CLK ON using UART driver's ioctl()
09-05 13:02:26.668: D/WCNSS_FILTER(6616): wcnss_acquire_wakelock
09-05 13:02:26.668: E/WCNSS_FILTER(6616): wcnss_acquire_wakelock wake lock not initialized
09-05 13:02:26.668: I/WCNSS_FILTER(6616): ibs_bt_device_wakeup: Writing IBS_WAKE_IND
09-05 13:02:26.674: I/WCNSS_FILTER(6616): ibs_recv_ibs_cmd: Received IBS_WAKE_ACK: 0xFC
09-05 13:02:26.695: I/cnss-daemon(421): RTM_NEWNEIGH message received: 28
09-05 13:02:26.695: E/cnss-daemon(421): Stale or unreachable neighbors, ndm state: 16
09-05 13:02:27.102: I/MSM-irqbalance(449): Decided to move IRQ271 from CPU2 to CPU3
09-05 13:02:27.836: I/WCNSS_FILTER(6616): ibs_wcnss_bt_device_sleep: TX Awake, Sending SLEEP_IND
09-05 13:02:27.837: I/WCNSS_FILTER(6616): ibs_msm_serial_clock_vote: vote UART CLK OFF using UART driver's ioctl()
09-05 13:02:27.837: D/WCNSS_FILTER(6616): wcnss_release_wakelock
09-05 13:02:27.837: E/WCNSS_FILTER(6616): wcnss_release_wakelock wake lock not initialized
09-05 13:02:29.365: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:29.603: D/LuxLevels(2065): bright hysteresis constant= 0.1, threshold=91.550705, lux=83.22791
09-05 13:02:29.604: D/LuxLevels(2065): dark hysteresis constant= 0.2, threshold=66.58233, lux=83.22791
09-05 13:02:29.707: I/GCoreUlr(3348): Starting BLE scan: mode: 2
09-05 13:02:29.711: I/BeaconBle(3348): Client requested scan, settings=BleSettings [scanMode=LOW_LATENCY, callbackType=ALL_MATCHES, reportDelayMillis=0, 2 filters, 0 clients, callingClientName=ULR]
09-05 13:02:29.799: I/BeaconBle(3348): 'L' hardware scan: 2 filters, scanMode=2, reportdelay=0, callback type=1, #clients=1
09-05 13:02:29.804: I/BeaconBle(3348): Starting scan on OS scanner. BT state: 15
09-05 13:02:29.837: D/BluetoothLeScanner(3348): onClientRegistered() - status=0 clientIf=4 mClientIf=0
09-05 13:02:29.882: I/WCNSS_FILTER(6616): ibs_msm_serial_clock_vote: vote UART CLK ON using UART driver's ioctl()
09-05 13:02:29.890: D/WCNSS_FILTER(6616): wcnss_acquire_wakelock
09-05 13:02:29.890: E/WCNSS_FILTER(6616): wcnss_acquire_wakelock wake lock not initialized
09-05 13:02:29.890: I/WCNSS_FILTER(6616): ibs_bt_device_wakeup: Writing IBS_WAKE_IND
09-05 13:02:29.895: I/WCNSS_FILTER(6616): ibs_recv_ibs_cmd: Received IBS_WAKE_ACK: 0xFC
09-05 13:02:29.930: D/BtGatt.GattService(6572): onScanParamSetupCompleted : 0
09-05 13:02:30.945: I/WCNSS_FILTER(6616): ibs_wcnss_bt_device_sleep: TX Awake, Sending SLEEP_IND
09-05 13:02:30.945: I/WCNSS_FILTER(6616): ibs_msm_serial_clock_vote: vote UART CLK OFF using UART driver's ioctl()
09-05 13:02:30.945: D/WCNSS_FILTER(6616): wcnss_release_wakelock
09-05 13:02:30.945: E/WCNSS_FILTER(6616): wcnss_release_wakelock wake lock not initialized
09-05 13:02:31.466: D/LuxLevels(2065): bright hysteresis constant= 0.1, threshold=100.73976, lux=91.5816
09-05 13:02:31.466: D/LuxLevels(2065): dark hysteresis constant= 0.2, threshold=73.26528, lux=91.5816
09-05 13:02:31.724: I/GCoreUlr(3348): Starting BLE scan: mode: 3
09-05 13:02:31.733: I/GCoreUlr(3348): BLE: collected 0 results
09-05 13:02:31.733: I/BeaconBle(3348): Client requested scan, settings=BleSettings [scanMode=ZERO_POWER, callbackType=ALL_MATCHES, reportDelayMillis=0, 2 filters, 0 clients, callingClientName=ULR]
09-05 13:02:31.791: I/BeaconBle(3348): Stopping scan on delegate scanner. BT state: 15
09-05 13:02:31.803: I/WCNSS_FILTER(6616): ibs_msm_serial_clock_vote: vote UART CLK ON using UART driver's ioctl()
09-05 13:02:31.814: D/WCNSS_FILTER(6616): wcnss_acquire_wakelock
09-05 13:02:31.814: E/WCNSS_FILTER(6616): wcnss_acquire_wakelock wake lock not initialized
09-05 13:02:31.814: I/WCNSS_FILTER(6616): ibs_bt_device_wakeup: Writing IBS_WAKE_IND
09-05 13:02:31.818: I/WCNSS_FILTER(6616): ibs_recv_ibs_cmd: Received IBS_WAKE_ACK: 0xFC
09-05 13:02:31.825: I/BeaconBle(3348): Resetting - new scanner available: true
09-05 13:02:31.826: I/BeaconBle(3348): ZERO_POWER is disabled.
09-05 13:02:31.827: I/BeaconBle(3348): 'L' hardware scan: scan stopped, no powered clients
09-05 13:02:32.106: I/MSM-irqbalance(449): Decided to move IRQ48 from CPU2 to CPU3
09-05 13:02:32.387: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:32.827: I/WCNSS_FILTER(6616): ibs_wcnss_bt_device_sleep: TX Awake, Sending SLEEP_IND
09-05 13:02:32.828: I/WCNSS_FILTER(6616): ibs_msm_serial_clock_vote: vote UART CLK OFF using UART driver's ioctl()
09-05 13:02:32.828: D/WCNSS_FILTER(6616): wcnss_release_wakelock
09-05 13:02:32.828: E/WCNSS_FILTER(6616): wcnss_release_wakelock wake lock not initialized
09-05 13:02:35.413: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:38.436: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:41.468: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:44.497: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:44.874: W/QCNEJ(3387): |CORE| CNE received unexpected action: android.intent.action.BATTERY_CHANGED
09-05 13:02:44.893: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:44.895: D/WifiService(2065):  reportActivityInfo:  rxIdleCur=0 rxCur=0 txCur=0 voltage=3.7 on_time=-1059227846 tx_time=-702956854 tx_time_per_level=[] rx_time=-1013762765 rxIdleTime=657491773 energy=0
09-05 13:02:44.904: E/BatteryStatsService(2065): no controller energy info supplied
09-05 13:02:44.905: E/BatteryStatsService(2065): no controller energy info supplied
09-05 13:02:44.944: E/BatteryStatsService(2065): power: Missing API
09-05 13:02:44.949: E/KernelUidCpuTimeReader(2065): Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
09-05 13:02:44.966: E/BatteryStatsService(2065): modem info is invalid: ModemActivityInfo{ mTimestamp=7470189 mSleepTimeMs=5817114 mIdleTimeMs=-3976877 mTxTimeMs[]=[6, 96, 136, 100, 408] mRxTimeMs=43568 mEnergyUsed=0}
09-05 13:02:44.982: E/KernelUidCpuTimeReader(2065): Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
09-05 13:02:47.521: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:02:48.322: I/cnss-daemon(421): RTM_NEWNEIGH message received: 28
09-05 13:02:48.323: E/cnss-daemon(421): Stale or unreachable neighbors, ndm state: 4

```

And these logs comes from an own ARCore Unity3D project with unitygar modified:

```
09-05 13:06:04.681: E/Unity(19459): EntryPointNotFoundException: CallsToConnectWithoutMatchingDisconnect
09-05 13:06:04.681: E/Unity(19459):   at (wrapper managed-to-native) GoogleARCoreInternal.TangoClientApi/ExternApi:CallsToConnectWithoutMatchingDisconnect ()
09-05 13:06:04.681: E/Unity(19459):   at GoogleARCoreInternal.TangoClientApi.CallsToConnectWithoutMatchingDisconnect () [0x00000] in <filename unknown>:0 
09-05 13:06:04.681: E/Unity(19459):   at GoogleARCore.SessionComponent+<_AttemptRecoverIfInvalidState>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
09-05 13:06:04.681: E/Unity(19459):   at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
09-05 13:06:04.681: E/Unity(19459): UnityEngine.MonoBehaviour:StartCoroutine_Auto_Internal(IEnumerator)
09-05 13:06:04.681: E/Unity(19459): UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
09-05 13:06:04.681: E/Unity(19459): GoogleARCore.SessionComponent:Awake()
09-05 13:06:04.681: E/Unity(19459):  
09-05 13:06:04.681: E/Unity(19459): (Filename:  Line: -1)
09-05 13:06:04.697: E/Unity(19459): EntryPointNotFoundException: TangoService_isSupported
09-05 13:06:04.697: E/Unity(19459):   at (wrapper managed-to-native) GoogleARCoreInternal.TangoClientApi/ExternApi:TangoService_isSupported (bool&)
09-05 13:06:04.697: E/Unity(19459):   at GoogleARCoreInternal.TangoClientApi.TangoService_IsSupported (System.Boolean& isSupported) [0x00000] in <filename unknown>:0 
09-05 13:06:04.697: E/Unity(19459):   at GoogleARCore.SessionComponent.Connect (GoogleARCore.SessionConfig sessionConfig) [0x00000] in <filename unknown>:0 
09-05 13:06:04.697: E/Unity(19459):   at GoogleARCore.SessionComponent.Connect () [0x00000] in <filename unknown>:0 
09-05 13:06:04.697: E/Unity(19459):   at GoogleARCore.SessionComponent.Awake () [0x00000] in <filename unknown>:0 
09-05 13:06:04.697: E/Unity(19459):  
09-05 13:06:04.697: E/Unity(19459): (Filename:  Line: -1)
09-05 13:06:04.947: W/SensorService(2065): sensor 00000001 already enabled in connection 0x7f569cd6c0 (ignoring)
09-05 13:06:05.015: I/AudioPolicyManagerCustom(409): setting force DEEP buffer now 
09-05 13:06:05.017: I/AudioPolicyManagerCustom(409): setting force DEEP buffer now 
09-05 13:06:05.020: I/AudioPolicyManagerCustom(409): setting force DEEP buffer now 
09-05 13:06:05.032: I/AudioPolicyManagerCustom(409): offload disabled by audio.offload.disable=1
09-05 13:06:05.032: I/AudioPolicyManagerCustom(409): Direct PCM is disabled for this request
09-05 13:06:05.032: I/AudioPolicyManagerCustom(409): setting force DEEP buffer now 
09-05 13:06:05.035: D/AudioTrack(19459): Client defaulted notificationFrames to 887 for frameCount 2662
09-05 13:06:05.136: E/wifi(2065): Ignoring invalid tx_level info in radio_stats
09-05 13:06:05.198: A/tango(19459): jni_helper.cc:19 'vm' Must be non NULL
09-05 13:06:05.199: A/libc(19459): Fatal signal 6 (SIGABRT), code -6 in tid 19475 (UnityMain)
09-05 13:06:05.200: W/(336): debuggerd: handling request: pid=19459 uid=10100 gid=10100 tid=19475
09-05 13:06:05.314: A/DEBUG(19527): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-05 13:06:05.314: A/DEBUG(19527): LineageOS Version: '14.1-20170823-NIGHTLY-libra'
09-05 13:06:05.314: A/DEBUG(19527): Build fingerprint: 'Xiaomi/libra/libra:7.0/NRD90M/V8.2.3.0.NXKCNEC:user/release-keys'
09-05 13:06:05.315: A/DEBUG(19527): Revision: '0'
09-05 13:06:05.315: A/DEBUG(19527): ABI: 'arm'
09-05 13:06:05.315: A/DEBUG(19527): pid: 19459, tid: 19475, name: UnityMain  >>> com.xaviscript.arcoretest <<<
09-05 13:06:05.315: A/DEBUG(19527): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-05 13:06:05.326: A/DEBUG(19527): Abort message: 'jni_helper.cc:19 'vm' Must be non NULL'
09-05 13:06:05.326: A/DEBUG(19527):     r0 00000000  r1 00004c13  r2 00000006  r3 00000008
09-05 13:06:05.326: A/DEBUG(19527):     r4 f2ee6978  r5 00000006  r6 f2ee6920  r7 0000010c
09-05 13:06:05.326: A/DEBUG(19527):     r8 f2ee4af0  r9 f2ee4aec  sl 0000018d  fp 00000000
09-05 13:06:05.326: A/DEBUG(19527):     ip 00000002  sp f2ee4670  lr f66dd127  pc f66df984  cpsr 200f0010
09-05 13:06:05.337: A/DEBUG(19527): backtrace:
09-05 13:06:05.337: A/DEBUG(19527):     #00 pc 0004a984  /system/lib/libc.so (tgkill+12)
09-05 13:06:05.337: A/DEBUG(19527):     #01 pc 00048123  /system/lib/libc.so (pthread_kill+34)
09-05 13:06:05.337: A/DEBUG(19527):     #02 pc 0001d985  /system/lib/libc.so (raise+10)
09-05 13:06:05.337: A/DEBUG(19527):     #03 pc 000194d1  /system/lib/libc.so (__libc_android_abort+34)
09-05 13:06:05.337: A/DEBUG(19527):     #04 pc 00017118  /system/lib/libc.so (abort+4)
09-05 13:06:05.337: A/DEBUG(19527):     #05 pc 00005841  /system/lib/liblog.so (__android_log_assert+112)
09-05 13:06:05.338: A/DEBUG(19527):     #06 pc 00009d1d  /data/app/com.xaviscript.arcoretest-1/lib/arm/libtango_client_api2.so
09-05 13:06:05.338: A/DEBUG(19527):     #07 pc 000123a9  /data/app/com.xaviscript.arcoretest-1/lib/arm/libtango_client_api2.so
09-05 13:06:05.338: A/DEBUG(19527):     #08 pc 00009e91  /data/app/com.xaviscript.arcoretest-1/lib/arm/libtango_client_api2.so (TangoService_getPoseAtTime+40)
09-05 13:06:05.338: A/DEBUG(19527):     #09 pc 008c50a0  /data/app/com.xaviscript.arcoretest-1/lib/arm/libunity.so
09-05 13:06:05.338: A/DEBUG(19527):     #10 pc 008c4f0c  /data/app/com.xaviscript.arcoretest-1/lib/arm/libunity.so
09-05 13:06:05.338: A/DEBUG(19527):     #11 pc 008cc0e4  /data/app/com.xaviscript.arcoretest-1/lib/arm/libunity.so
09-05 13:06:05.338: A/DEBUG(19527):     #12 pc 0000629c  <anonymous:d868e000>

```

great job, and let's do this :D

**Comment by tomthecarrot** [comment]
Thanks for sharing your log! It is helpful in debugging the issue.
