### ISSUE TITLE
OnePlus 3 not working

### ISSUE THREAD

**Issue by Mpk605** [tomthecarrot/arcore-for-all#47]
The app launch but, the camera don't

Here's the logcat :

09-05 21:43:40.165 31785-31785/com.google.ar.core.examples.java.helloar I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
09-05 21:43:40.187 31785-31785/com.google.ar.core.examples.java.helloar D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.google.tango-1/lib/arm64:/system/fake-libs64:/data/app/com.google.tango-1/base.apk!/lib/arm64-v8a for namespace 0x7f890f10f0
09-05 21:43:40.224 31785-31785/com.google.ar.core.examples.java.helloar I/ndk_camera: Starting native camera system initialization.
09-05 21:43:40.227 31785-31785/com.google.ar.core.examples.java.helloar D/ndk_camera: Camera 0 has 88 metadata tags
09-05 21:43:40.227 31785-31785/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
09-05 21:43:40.227 31785-31785/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1310721 for camera 0 with error code -10004
09-05 21:43:40.227 31785-31785/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
09-05 21:43:40.227 31785-31785/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1638401 for camera 0 with error code -10004
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar D/ndk_camera: Camera 1 has 87 metadata tags
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1310721 for camera 1 with error code -10004
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1638401 for camera 1 with error code -10004
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar I/ndk_camera: Camera system initialized successfully with 2 cameras.
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: Camera system initilized.
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar E/tango_camera_native: 2 is not a valid camera index.
09-05 21:43:40.228 31785-31785/com.google.ar.core.examples.java.helloar E/tango_camera_native: 3 is not a valid camera index.
09-05 21:43:40.239 31785-31785/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching texture_window 0x7f8a455c10
09-05 21:43:40.239 31785-31785/com.google.ar.core.examples.java.helloar D/TangoVhs: about to bind as vhs
09-05 21:43:40.254 31785-31785/com.google.ar.core.examples.java.helloar D/TangoVhs: finished bind as vhs
09-05 21:43:40.266 31785-31917/com.google.ar.core.examples.java.helloar D/AppTracker: App Event: start
09-05 21:43:40.727 31785-31785/com.google.ar.core.examples.java.helloar D/TangoVhs: connected
09-05 21:43:40.733 31785-31926/com.google.ar.core.examples.java.helloar I/TangoCameraNative: Tango VHS Ready
09-05 21:43:41.196 31785-31926/com.google.ar.core.examples.java.helloar W/System.err: android.os.DeadObjectException
09-05 21:43:41.202 31785-31926/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
09-05 21:43:41.202 31785-31926/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transact(Binder.java:651)
09-05 21:43:41.202 31785-31926/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
09-05 21:43:41.202 31785-31926/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
09-05 21:43:41.202 31785-31926/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
09-05 21:43:41.202 31785-31926/com.google.ar.core.examples.java.helloar W/System.err:     at java.lang.Thread.run(Thread.java:761)
09-05 21:43:41.203 31785-31926/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
09-05 21:43:41.203 31785-31926/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases
![screenshot](https://user-images.githubusercontent.com/17913217/30080346-994da34e-9283-11e7-917e-bf5b3945a889.png)

**Comment by manjogsingh** [comment]
![screenshot_20170915-193003](https://user-images.githubusercontent.com/11537801/30485893-6e3fc954-9a4c-11e7-8430-ca7d85271a3f.jpg)
[build-modified.prop.txt](https://github.com/tomthecarrot/arcore-for-all/files/1306558/build-modified.prop.txt)

Got it working with your modified arcore apk and unitygar.aar with few tweaks in build.prop
