### ISSUE TITLE
Nexus 5X

### ISSUE THREAD

**Issue by hannesa2** [tomthecarrot/arcore-for-all#73]
Does someone manage to run this with Nexus 5X ?
If yes, please share how to manage it, I wasn't able to do so

**Comment by markradomski** [comment]
Just tried on my Nexus 5X.
![nexus5x-arcore](https://user-images.githubusercontent.com/1411480/30624070-82536d1e-9de5-11e7-946a-52d10c177038.png)

**Comment by LvWind** [comment]
Not working on 5X(Android O)

```
10-13 16:45:43.371 1321-1333/com.google.ar.core.examples.java.helloar I/zygote64: After code cache collection, code=30KB, data=21KB
10-13 16:45:43.371 1321-1333/com.google.ar.core.examples.java.helloar I/zygote64: Increasing code cache capacity to 128KB
10-13 16:45:44.079 1321-1770/com.google.ar.core.examples.java.helloar W/System.err: android.os.DeadObjectException
10-13 16:45:44.079 1321-1770/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
10-13 16:45:44.080 1321-1770/com.google.ar.core.examples.java.helloar W/System.err:     at android.os.BinderProxy.transact(Binder.java:748)
10-13 16:45:44.080 1321-1770/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
10-13 16:45:44.080 1321-1770/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
10-13 16:45:44.081 1321-1770/com.google.ar.core.examples.java.helloar W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
10-13 16:45:44.081 1321-1770/com.google.ar.core.examples.java.helloar W/System.err:     at java.lang.Thread.run(Thread.java:764)
10-13 16:45:44.088 1321-1770/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
10-13 16:45:44.088 1321-1770/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases
10-13 16:45:44.133 1321-1333/com.google.ar.core.examples.java.helloar I/zygote64: Do partial code cache collection, code=61KB, data=38KB
10-13 16:45:44.133 1321-1333/com.google.ar.core.examples.java.helloar I/zygote64: After code cache collection, code=57KB, data=37KB
10-13 16:45:44.133 1321-1333/com.google.ar.core.examples.java.helloar I/zygote64: Increasing code cache capacity to 256KB
10-13 16:45:44.304 1321-1321/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 77 frames!  The application may be doing too much work on its main thread.
10-13 16:45:45.196 1321-1321/com.google.ar.core.examples.java.helloar D/TangoVhs: connected
10-13 16:45:45.197 1321-2341/com.google.ar.core.examples.java.helloar I/TangoCameraNative: Tango VHS Ready
10-13 16:45:45.203 1321-2341/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
10-13 16:45:45.203 1321-2341/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching tracking_window 0x795aa48010
```

**Comment by miquelferrarons** [comment]
Same here:

10-30 15:57:12.378 26275-26275/? I/zygote64: Late-enabling -Xcheck:jni
10-30 15:57:12.661 26275-26275/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
10-30 15:57:12.709 26275-26275/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
10-30 15:57:12.710 26275-26275/com.google.ar.core.examples.java.helloar I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
10-30 15:57:12.711 26275-26275/com.google.ar.core.examples.java.helloar E/Tango: Java version of Tango Service not found, falling back to tangoservice_d.
10-30 15:57:12.712 26275-26275/com.google.ar.core.examples.java.helloar E/zygote64: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
10-30 15:57:12.714 26275-26275/com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.google.ar.core.examples.java.helloar, PID: 26275
                                                                                          java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                                                              at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                                                              at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                                                              at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                                                              at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                                                              at com.google.ar.core.Session.resume(Session.java:153)
                                                                                              at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:136)
                                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                                                                                              at android.app.Activity.performResume(Activity.java:7079)
                                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
                                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
                                                                                              at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
