### ISSUE TITLE
Not working on nokia 6

### ISSUE THREAD

**Issue by APLdev** [tomthecarrot/arcore-for-all#92]
11-07 00:26:42.128 7050-7050/? I/art: Late-enabling -Xcheck:jni
11-07 00:26:42.184 7050-7050/com.google.ar.core.examples.java.helloar W/System: ClassLoader referenced unknown path: /data/app/com.google.ar.core.examples.java.helloar-2/lib/arm64
11-07 00:26:42.224 7050-7050/com.google.ar.core.examples.java.helloar W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
11-07 00:26:42.267 7050-7050/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
11-07 00:26:42.292 7050-7050/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable. Just kidding! ;)
11-07 00:26:42.294 7050-7050/com.google.ar.core.examples.java.helloar I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
11-07 00:26:42.311 7050-7050/com.google.ar.core.examples.java.helloar D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.google.tango-1/lib/arm64:/system/fake-libs64:/data/app/com.google.tango-1/base.apk!/lib/arm64-v8a for namespace 0x7f865080f0
11-07 00:26:42.346 7050-7050/com.google.ar.core.examples.java.helloar I/ndk_camera: Starting native camera system initialization.
11-07 00:26:42.350 7050-7050/com.google.ar.core.examples.java.helloar D/ndk_camera: Camera 0 has 88 metadata tags
11-07 00:26:42.350 7050-7050/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
11-07 00:26:42.350 7050-7050/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1310721 for camera 0 with error code -10004
11-07 00:26:42.350 7050-7050/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
11-07 00:26:42.350 7050-7050/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1638401 for camera 0 with error code -10004
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar D/ndk_camera: Camera 1 has 88 metadata tags
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1310721 for camera 1 with error code -10004
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar E/ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar W/ndk_camera: Failed to get metadata tag 1638401 for camera 1 with error code -10004
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar I/ndk_camera: Camera system initialized successfully with 2 cameras.
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar W/tango_camera_native_jni: Camera system initilized.
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar E/tango_camera_native: 2 is not a valid camera index.
11-07 00:26:42.351 7050-7050/com.google.ar.core.examples.java.helloar E/tango_camera_native: 3 is not a valid camera index.
11-07 00:26:42.359 7050-7050/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching texture_window 0x7f82a55c10
11-07 00:26:42.360 7050-7050/com.google.ar.core.examples.java.helloar D/TangoVhs: about to bind as vhs
11-07 00:26:42.368 7050-7050/com.google.ar.core.examples.java.helloar D/TangoVhs: finished bind as vhs
11-07 00:26:42.388 7050-7050/com.google.ar.core.examples.java.helloar I/HAL: loaded HAL id=gralloc path=/system/lib64/hw/gralloc.msm8937.so hmi=0x7fdfe132b0 handle=0x2c0a979e524d04c3
11-07 00:26:42.396 7050-7050/com.google.ar.core.examples.java.helloar D/TangoVhs: connected
11-07 00:26:42.397 7050-7099/com.google.ar.core.examples.java.helloar I/TangoCameraNative: Tango VHS Ready
11-07 00:26:42.416 7050-7097/com.google.ar.core.examples.java.helloar I/Adreno: QUALCOMM build                   : 3b35bac, Ie23f154500
                                                                                Build Date                       : 09/05/17
                                                                                OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                                Local Branch                     : 
                                                                                Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
                                                                                Remote Branch                    : NONE
                                                                                Reconstruct Branch               : NOTHING
11-07 00:26:42.423 7050-7097/com.google.ar.core.examples.java.helloar I/OpenGLRenderer: Initialized EGL, version 1.4
11-07 00:26:42.423 7050-7097/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: Swap behavior 1
11-07 00:26:42.426 7050-7099/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
11-07 00:26:42.426 7050-7099/com.google.ar.core.examples.java.helloar I/tango_camera_native_jni: Attaching tracking_window 0x7f82a58610
11-07 00:26:43.441 7050-7050/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread.
11-07 00:26:46.049 7050-7055/com.google.ar.core.examples.java.helloar I/art: Do partial code cache collection, code=30KB, data=29KB
11-07 00:26:46.050 7050-7055/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=25KB, data=27KB
11-07 00:26:46.050 7050-7055/com.google.ar.core.examples.java.helloar I/art: Increasing code cache capacity to 128KB

**Comment by peitaosu** [comment]
```
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
D/TangoVhs: connected
I/TangoCameraNative: Tango VHS Ready
W/System.err: android.os.DeadObjectException
W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
W/System.err:     at android.os.BinderProxy.transact(Binder.java:615)
W/System.err:     at com.google.atap.tangoservice.ITangoVhs$Stub$Proxy.getTrackingSurface(ITangoVhs.java:111)
W/System.err:     at com.google.atap.tangoservice.TangoVhs.getTrackingSurface(TangoVhs.java:81)
W/System.err:     at com.google.tango.jni.TangoCameraNative$2.run(TangoCameraNative.java:88)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
W/tango_camera_native_jni: tracking_surface == nullptr! Could break AR usecases
I/art: Do partial code cache collection, code=29KB, data=29KB
I/art: After code cache collection, code=25KB, data=26KB
I/art: Increasing code cache capacity to 128KB
V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@68a42cf
D/TangoVhs: connected
I/TangoCameraNative: Tango VHS Ready
I/tango_camera_native_jni: jint Java_com_google_tango_jni_TangoCameraNative_ConnectVhs(JNIEnv*, jobject, jobject, jobject)
I/tango_camera_native_jni: Attaching tracking_window 0x7f8104ea10
Application terminated.
```

Different logs, looks like performance issue?
